name: podcast_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_database: ^10.4.10
  cloud_firestore: ^4.15.9
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  inspector: ^2.1.0
  flutter_soloud: ^1.2.5
  record: ^5.0.5
  path_provider: ^2.1.2
  audio_wave: ^0.1.5
  lottie: ^3.1.0
  audio_video_progress_bar: ^2.0.2
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  


flutter:

  uses-material-design: true

  assets:
    - assets/